server:
    port: 9091

spring:
    application:
        name: gateway
    cloud:
        gateway:
            enabled: true
            routes:
                - id: book
                  uri: http://localhost:8085
                  predicates:
                      - Path=/api/v1/book/**
                - id: order
                  uri: http://localhost:8087
                  predicates:
                      - Path=/api/v1/order/**
                - id: auth
                  uri: http://localhost:8089
                  predicates:
                      - Path=/api/v1/auth/**
#                  filters:
#                      - StripPrefix=2

logging:
    file:
        name: D:/log/gateway.log
    level:
        springfox: info
        cn.edu.sgu.www.gateway: debug