server:
    port: 9091

spring:
  application:
    name: gateway_server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: bookservice
          uri: lb://bookservice
          predicates:
            - Path=/api/v1/book/**
        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Path=/api/v1/order/**
        - id: authservice
          uri: lb://authservice
          predicates:
            - Path=/api/v1/auth/**

logging:
    file:
        name: D:/log/gateway.log
    level:
        springfox: info
        cn.edu.sgu.www.gateway: debug